plugins {
    id 'java'
}

group = 'dev'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform(libs.junit.bom.platform)
    testImplementation libs.junit.jupiter
    testRuntimeOnly libs.junit.platform.launcher
    testImplementation libs.mockito.core

    implementation libs.guava
    implementation libs.logback.classic

    implementation libs.jackson.databind

    implementation libs.sim.math
    implementation libs.heart

    implementation project(':galaxy-domain')
    implementation project(':hex-grid')
}

test {
    useJUnitPlatform()
}
